### ISSUE TITLE
[Fix needed] Skill inheritance on Sortie does not show deployed units

### ISSUE THREAD

**Issue by Deklou** [Raytwo/Cobalt#12]
On v0.19.0. 
I don't know if this is an issue, but in the inheritance skills menu, only unselected unit can inherit skills.
for example, that are my units in my current run 
![image](https://github.com/Raytwo/Cobalt/assets/139881388/8a37d689-df44-45ae-b655-6b77073df1d2)

and that s what the menu shows me 
![image](https://github.com/Raytwo/Cobalt/assets/139881388/17821479-20bc-406f-9c95-c8873ec181a6)

also, i don't know if this is the right place to ask it, but do you plan to add a save option (to replace bookmark) in maddening?
my game keeps crashing on ryujinx when a map takes too long to finish, and i m sure i m not the only one with this problem.

**Comment by Deklou** [comment]
I get your point. It can make the challenge of maddening mode a bit too trivial if you abuse saving and reloading. 
But I allowed myself to request it because, in my opinion, adding somniel functionalities to the pre-battle menu also changes the intented game design in certain ways.
If you want to do a no somniel run, with the latest version of Cobalt, you have access to forging weapons and inheriting skills, which completely changes the point of doing this type of run. 
it is a self imposed challenge, but i think it follows the same kind of logic. Those who want to use it can use it, and those who want to keep part of the challenge can play as if these additions didn't exist
Maybe replacing the bookmark system entirely is a bit too much. It all depends on the implementation.
In any case i think cobalt is a great tool, congratulations to you and keep up the good work !

**Comment by Raytwo** [comment]
> If you want to do a no somniel run, with the latest version of Cobalt, you have access to forging weapons and inheriting skills, which completely changes the point of doing this type of run.

I mean, I guess that's true, but you'd have to have to self-restrain to not use the armory and item shop either then since these are technically Somniel facilities :p I also don't allow for these to be enabled in missions where they are not available, so the gameplay-story synergy is still respected in a way.
Plus a "no somniel run" is technically not the intended way of playing the game but a self-imposed challenge, so that's on you to respect your own rules. 
I don't think the intend behind not adding the smithy to the menu was to make it more challenging, just some missing QoL that slipped through, since they added skill inheritance to the arena at some point down the road.

I'll ask around for people's opinion on this and get back to you, as I said I'm not against the idea, I just don't want someone barking at me later that I ruined the game for them.

> In any case i think cobalt is a great tool, congratulations to you and keep up the good work !
Merci !

**Comment by Raytwo** [comment]
Oops, didn't mean to close this.

**Comment by Deklou** [comment]
I think i might need some help with this code patch.
I tried to use it as a cheat in ryujinx, but when i boot the game, it doesn't change anything. (same for other cheats btw)

**Comment by Deklou** [comment]
Thank you, its works !

**Comment by Deklou** [comment]
I was wondering, what are you planning for cobalt in the future ? and for engage overall
and also when you need advice on the game, who do you ask?

**Comment by Raytwo** [comment]
> I was wondering, what are you planning for cobalt in the future ? and for engage overall
For now the focus is mostling on improving what's already there, so more localization, more MSBT support, more script support and making things faster/more robust all around for what's to come after: allowing mod makers to make their own edits to the code like Cobalt does.

Some features that will be worked on when the need comes up are a custom config menu in the Cobalt menu, an About page, listing the mods on the SD to enable/disable them from the game, allowing to add more supports to the game, researching music addition, ... there are plenty of things that can be done but only a few hands to make them happen.

**Comment by Raytwo** [comment]
Fixed as of Cobalt v0.35.1
